### PR TITLE
2909 splitpagelayoutpane accepts an id but doesnt apply it

### LINKED ISSUE #2909: SplitPageLayout.Pane accepts an id but doesn't apply it.
### Description

SplitPageLayout.Pane accepts an id as a prop, but doesn't apply it to any element

### Steps to reproduce

Add an id to SplitPageLayout example:

```
<Box sx={{height: 320, overflowY: 'auto', border: '1px solid', borderColor: 'border.default'}}>
  <SplitPageLayout>
    <SplitPageLayout.Header>
      <Placeholder label="Header" height={64} />
    </SplitPageLayout.Header>
    <SplitPageLayout.Pane id="test-id">
      <Placeholder label="Pane" height={120} />
    </SplitPageLayout.Pane>
    <SplitPageLayout.Content>
      <Placeholder label="Content" height={420} />
    </SplitPageLayout.Content>
    <SplitPageLayout.Footer>
      <Placeholder label="Footer" height={64} />
    </SplitPageLayout.Footer>
  </SplitPageLayout>
</Box>
```

And observe that it does not appear in the DOM.

### Version

v35.19

### Browser

Chrome

### PR DESCRIPTION
**Pull request by green6erry**
Describe your changes here - PageLayout/SplitPageLayout.Pane component is given an `id` attribute, it is applied to the component when rendered.

Closes #2909  (type the issue number after # if applicable; otherwise remove this line)

### Screenshots

Please provide before/after screenshots for any visual changes
This is just showing the updated story where the id can be passed to the PageLayout/SplitPageLayout.Pane component
image

### Merge checklist

- [x] Added/updated tests
- [x] Added/updated documentation
- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Safari
- [x] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

File: src/PageLayout/PageLayout.tsx [hunk 1]
```diff
@@ -736,6 +736,7 @@ const Pane = React.forwardRef<HTMLDivElement, React.PropsWithChildren<PageLayout
               '--pane-max-width-diff': '959px',
             },
           })}
+          {...(id && {id: paneId})}
```
Comment (colebemis) [inline src/PageLayout/PageLayout.tsx:739]: How do you feel about simplifying to this?

```suggestion
          id={id}
```

If `id` is `undefined`, it won't pass `id` to the underlying component.

If `id` is defined, `paneId` and `id` will be the same, so we can use either.

**Review by colebemis — APPROVED** [review]
Looks great! Just left a non-blocking comment about simplifying it a bit.
