### PR TITLE
Move `flex-shrink: 0` to `BaseVisualContainer`.

### LINKED ISSUE #1595: Misalignment of items in single-select `<ActionList />` when an item wraps
**Describe the bug**

If a single-select `<ActionList />` component contains an item that wraps, then the left alignment of the that item can be off compared to the rest of the items in the list.

Image showing misaslignment of the a wrapping item

**To Reproduce**
I altered the `SingleSelectListStory` a little bit to reproduce the problem (adding the dividers isn't necessary, but I think it helps illustrate the problem. 

```diff
@dmarcey ➜ /workspaces/react (main ✗) $ git diff src/stories/ActionList.stories.tsx 
diff --git a/src/stories/ActionList.stories.tsx b/src/stories/ActionList.stories.tsx
index 46e21e2c..0c03ccbe 100644
--- a/src/stories/ActionList.stories.tsx
+++ b/src/stories/ActionList.stories.tsx
@@ -106,13 +106,15 @@ const selectListItems = new Array(6).fill(undefined).map((_, i) => {
     id: i
   }
 })
+selectListItems.push({id: 6, text: 'Item with a really really long text value that should wrap'})
 
 export function SingleSelectListStory(): JSX.Element {
   return (
     <>
       <h1>Single Select List</h1>
-      <ErsatzOverlay>
+      <ErsatzOverlay maxWidth="300px">
         <ActionList
+          showItemDividers={true}
           items={selectListItems.map((item, index) => ({
             ...item,
             selected: index === 1
```

**Expected behavior**
The items should be left-aligned, even if an item wraps.

I believe that adding a `flex-shrink: 0` to `BaseVisualContainer` should fix the issue, which is what I did in the screenshot below:

Image showing list items aligned

### PR DESCRIPTION
**Pull request by dmarcey**
This is to address a bug where in a single-select action menu, if an item wraps, it will become misaligned with other items in the list.

Closes #1595 

### Screenshots

Before:
Image showing misaslignment of the a wrapping item

After:
Image showing list items aligned

Story changes (not included in PR) that I made to repro this scenario:

```diff
@dmarcey ➜ /workspaces/react (main ✗) $ git diff src/stories/ActionList.stories.tsx 
diff --git a/src/stories/ActionList.stories.tsx b/src/stories/ActionList.stories.tsx
index 46e21e2c..0c03ccbe 100644
--- a/src/stories/ActionList.stories.tsx
+++ b/src/stories/ActionList.stories.tsx
@@ -106,13 +106,15 @@ const selectListItems = new Array(6).fill(undefined).map((_, i) => {
     id: i
   }
 })
+selectListItems.push({id: 6, text: 'Item with a really really long text value that should wrap'})
 
 export function SingleSelectListStory(): JSX.Element {
   return (
     <>
       <h1>Single Select List</h1>
-      <ErsatzOverlay>
+      <ErsatzOverlay maxWidth="300px">
         <ActionList
+          showItemDividers={true}
           items={selectListItems.map((item, index) => ({
             ...item,
             selected: index === 1
```

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Safari
- [x] Tested in Edge

### CODE REVIEW

File: src/ActionList/Item.tsx [hunk 1]
```diff
@@ -295,6 +295,7 @@ const BaseVisualContainer = styled.div<{variant?: ItemProps['variant']; disabled
   height: 20px;
   width: ${get('space.3')};
   margin-right: ${get('space.2')};
+  flex-shrink: 0;
```
Comment (dmarcey) [inline src/ActionList/Item.tsx:298]: Instead of this change, I think we could move the `flex-shrink: 0` to an `sx` prop on the `<BaseVisualContainer />` used in `<Item />` for single-select action lists, but this seemed like a more correct fix.

Happy to switch to the more targeted approach if we feel like it is safer.

**Review by siddharthkp — APPROVED** [review]
LGTM!

**Comment by siddharthkp** [comment]
@dmarcey Sorry for letting this go stale! Do you mind updating this with `main` and i'll merge this?

**Comment by dmarcey** [comment]
> @dmarcey Sorry for letting this go stale! Do you mind updating this with `main` and i'll merge this?

Thanks @siddharthkp! Rebase complete and CI is green!
