### PR TITLE
[Dialog] Replace deprecated `Button` for current one

### LINKED ISSUE #3062: Focus not appearing on non-standard dialog button (re-opened after revert)
### Description

Focus does not appear at all on Primary and Danger buttons in a Dialog Footer

### Steps to reproduce

1. Go to https://primer.style/react/storybook/?path=/story/components-dialog--stress-test
2. Open the Dialog
3. Use tab to move through the footer buttons
4. Notice that once you get to the danger and primary buttons, focus is no longer visible

### Version

v35.22

### Browser

Chrome

### PR DESCRIPTION
**Pull request by ItzaMi**
Describe your changes here.

Closes #3062

- replaces deprecated `button` for the current one 
- updates logic for focus (please correct me if I missed something in the use case but what's currently in `main` doesn't allow to navigate to the `1st` button)

### Screenshots

_Before_

https://user-images.githubusercontent.com/30603437/228054811-796dee74-1c23-40e2-a33c-a402d927a636.mp4

_After_

https://user-images.githubusercontent.com/30603437/228054901-a79e9608-ca73-4f92-83b7-37b88cdbb3eb.mp4

### Merge checklist

- [x] Added/updated tests
- [x] Added/updated documentation
- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Safari
- [x] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Review by mperrotti — COMMENTED** [review]
This seems good to me, but I'd be more comfortable if @broccolinisoup reviews since she's more familiar with this component.

File: src/Dialog/Dialog.tsx [hunk 1]
```diff
@@ -366,15 +366,10 @@ const Footer = styled.div<SxProp>`
...
-  normal: Button,
-  primary: ButtonPrimary,
-  danger: ButtonDanger,
-}
 const Buttons: React.FC<React.PropsWithChildren<{buttons: DialogButtonProps[]}>> = ({buttons}) => {
   const autoFocusRef = useProvidedRefOrCreate<HTMLButtonElement>(buttons.find(button => button.autoFocus)?.ref)
-  let autoFocusCount = 0
-  const [hasRendered, setHasRendered] = useState(0)
+  let autoFocusCount = -1
+  const [hasRendered, setHasRendered] = useState(-1)
```
Comment (broccolinisoup) [inline src/Dialog/Dialog.tsx:372]: I think we should take this back. This manages auto focus when there is a footer button that has `autoFocus: true` prop.

[Story reference](https://github.com/primer/react/blob/main/src/stories/Dialog.stories.tsx#L129), [docs reference](https://primer.style/react/drafts/Dialog#keyboard)

File: src/Dialog/Dialog.tsx [hunk 2]
```diff
@@ -387,17 +382,16 @@ const Buttons: React.FC<React.PropsWithChildren<{buttons: DialogButtonProps[]}>>
   return (
     <>
       {buttons.map((dialogButtonProps, index) => {
-        const {content, buttonType = 'normal', autoFocus = false, ...buttonProps} = dialogButtonProps
-        const ButtonElement = buttonTypes[buttonType]
+        const {children, buttonType = 'default', autoFocus = false, ...buttonProps} = dialogButtonProps
```
Comment (broccolinisoup) [inline src/Dialog/Dialog.tsx:385]: I also think maybe we shouldn't rename `content` to `children`. Because `content` here is more like a [button text content](https://github.com/primer/react/blob/main/src/stories/Dialog.stories.tsx#L192) rather than a typical [React children prop](https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children)

**Review by broccolinisoup — CHANGES_REQUESTED** [review]
@ItzaMi 👋🏻 Thank you so much for taking the time to push this PR 🙏🏻 I left some comments. Let me know if you have any concerns/questions 🙌🏻

File: src/Dialog/Dialog.tsx (hunk 1 above)
Comment (ItzaMi) [reply src/Dialog/Dialog.tsx:372]: I did this change mostly because I saw the following:
- opened the dialog
- pressed `TAB` once
- no button gets focus
- pressed `TAB` one more time
- focus is on the 2nd button

Felt a bit weird, don't know if it's intended but also seems out of scope of this PR so I'll rollback this change and can get tackled in a new issue, if that's the case

Comment (broccolinisoup) [reply src/Dialog/Dialog.tsx]: Hmm, interesting - I don't see this behaviour. Here is my local. I might be missing something but as you mentioned it is out of this Pr's scope so thank you for taking this back. 

https://user-images.githubusercontent.com/1446503/233222234-b03d6764-c020-452d-a2f1-6a5e7b642b82.mp4

_Video description: Dialog storybook page is on the screen and there is a button called "Open Dialog". User tabs into the button and opens the dialog and keep pressing the tab to move the trapped focus on the dialog._

File: src/Dialog/Dialog.tsx (hunk 2 above)
Comment (broccolinisoup) [reply src/Dialog/Dialog.tsx:385]: I am mainly concerned because a prop rename will potentially cause breaking changes and also Dialog props are a combined with `ButtonProps` so it would end up having two `children` props. https://github.com/primer/react/blob/main/src/Dialog/Dialog.tsx#L23

Same concern for renaming the `buttonType` option here as well https://github.com/primer/react/pull/3084/files#diff-7c9e4f2540e063c93f543e6eaa44cac7dc3b0e55a8fe81030c9e571f72950a3eR27

Would that be possible to revert these as well? And we can chat about them further if you are interested 😊

**Comment by broccolinisoup** [comment]
@ItzaMi Sorry for late respond! I left comments on the PR, let me know what you think 🙌🏻

File: src/Dialog/Dialog.tsx (hunk 2 above)
Comment (ItzaMi) [reply src/Dialog/Dialog.tsx:385]: > Same concern for renaming the buttonType option here as well https://github.com/primer/react/pull/3084/files#diff-7c9e4f2540e063c93f543e6eaa44cac7dc3b0e55a8fe81030c9e571f72950a3eR27

I might be looking at it wrong but I believe that this rename for the `buttonType` is compliant with the non-deprecated `Button` ( https://github.com/primer/react/blob/main/src/Button/types.ts#L11 )

Regarding the `children` vs `content`, should we then `Omit` `children` on this extension of `Button`? https://github.com/primer/react/pull/3084/files#diff-7c9e4f2540e063c93f543e6eaa44cac7dc3b0e55a8fe81030c9e571f72950a3eR23

Since we're using `content` for the prop on `DialogButtons` but `Button` has a `children`, there's a slight mismatch, at the moment, since, for example, the `footerButtons` on the `stories`, require a `content` and a `children` property.

Comment (joshblack) [reply src/Dialog/Dialog.tsx:385]: I wouldn't mind supporting `children` but definitely wanted to +1 keeping `content` available during this transition so we don't break any existing usage using `content`. Do either of you think this could be possible? Something like: `{children ?? content}` if we end up using both here, and keep `content` on the `DialogButtonProps`.

Just an idea, let me know what you think!

Comment (broccolinisoup) [reply src/Dialog/Dialog.tsx:385]: Thanks @joshblack! I love that suggestion! I played with the code a bit today to see how we can support both but the typescript is making trouble and needs `children` because `DialogButtonProps` has `children` as a mandatory prop through `Buttons`. Is there anything I am missing here? I would really love to support both in the transition period! Is there a way to make `Button` 's mandatory `children` prop optional in `DialogButtonProps`? 😬  Or any other way really.


@ItzaMi you are 💯 right on renaming the `buttonType` from being `normal` to `default` (sorry I missed that earlier) however this is still a breaking change and we really would love to merge this before the major release so following @joshblack's suggestion for supporting both, how about we add `default` as another option?

```
/**
   * The type of Button element to use
   */
  buttonType?: 'normal' | 'primary' | 'danger' | 'default'
```

And on the `<Button>` element, we could make sure we pass `default` even if we receive `normal`

```
<Button
....
variant={buttonType === 'normal' ? 'default' : buttonType}
...
>
```

Looking forward to hearing your thoughts! 🙌🏻

**Comment by broccolinisoup** [comment]
👋🏻 @ItzaMi Are you still happy to follow up with the PR? If not, all good! We are looking into resolving this soon so wanted to check in with you - let us know if you have any questions! Thanks for your work 🙏🏻

**Comment by ItzaMi** [comment]
> 👋🏻 @ItzaMi Are you still happy to follow up with the PR? If not, all good! We are looking into resolving this soon so wanted to check in with you - let us know if you have any questions! Thanks for your work 🙏🏻

Hey 👋  Absolute! Just did a commit with the `normal` changes. Regarding the `content / children`, how do we stand on that?

**Comment by broccolinisoup** [comment]
> > 👋🏻 @ItzaMi Are you still happy to follow up with the PR? If not, all good! We are looking into resolving this soon so wanted to check in with you - let us know if you have any questions! Thanks for your work 🙏🏻
> 
> Hey 👋 Absolute! Just did a commit with the `normal` changes. Regarding the `content / children`, how do we stand on that?

I think we should keep the `content` as is and omit the `children` prop. 

```
export type DialogButtonProps = Omit<ButtonProps, 'children'> & {
...
```

This way type system won't ask `children` prop and `content` will be rendered as `Button` component's children. I tried supporting both as mentioned [here](https://github.com/primer/react/pull/3084#discussion_r1184498387), but no luck. Let me know if you give that a try. Thanks!!

**Comment by ItzaMi** [comment]
> > > 👋🏻 @ItzaMi Are you still happy to follow up with the PR? If not, all good! We are looking into resolving this soon so wanted to check in with you - let us know if you have any questions! Thanks for your work 🙏🏻
> > 
> > 
> > Hey 👋 Absolute! Just did a commit with the `normal` changes. Regarding the `content / children`, how do we stand on that?
> 
> I think we should keep the `content` as is and omit the `children` prop.
> 
> ```
> export type DialogButtonProps = Omit<ButtonProps, 'children'> & {
> ...
> ```
> 
> This way type system won't ask `children` prop and `content` will be rendered as `Button` component's children. I tried supporting both as mentioned [here](https://github.com/primer/react/pull/3084#discussion_r1184498387), but no luck. Let me know if you give that a try. Thanks!!

Should be done now 👍

**Comment by broccolinisoup** [comment]
@ItzaMi Thanks!! We will also need to;
1) Update the snapshots as there are visual changes. You can do that with `npm run test -- -u` ([reference](https://github.com/primer/react/blob/main/contributor-docs/testing.md#running-tests)) 
2) [Add a changeset ](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#adding-changeset-to-your-pull-request)

Let me know if you need any help with either of those 🙌🏻 Thanks so much for your contribution 🙏🏻

**Comment by ItzaMi** [comment]
@broccolinisoup , I've done the required changes, hopefully everything is correct.
There are two snapshot tests that fail on update but I'm unsure on why they actually failed

```shell
 FAIL  src/__tests__/exports.test.ts
  ● Test suite failed to run

    Configuration error:

    Could not locate module ./component.module.css mapped as:
    jest-css-modules.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/\.css$/": "jest-css-modules"
      },
      "resolver": undefined
    }

      1 | import React from 'react'
      2 | import merge from 'classnames'
    > 3 | import classNames from './component.module.css'
        | ^
      4 |
      5 | export const Component: React.FC<React.HTMLProps<HTMLDivElement>> = ({className, ...props}) => {
      6 |   return <div className={merge(classNames.component, className)} {...props} />

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/resolver.js:759:17)
      at Object.require (src/drafts/CSSComponent/index.tsx:3:1)
      at Object.require (src/drafts/index.ts:56:1)
      at Object.require (src/__tests__/exports.test.ts:4:1)

 FAIL  src/__tests__/ConfirmationDialog.test.tsx
  ● Test suite failed to run

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'HTMLSpanElement'
        |     property '__reactFiber$pkbppatqhkq' -> object with constructor 'FiberNode'
        --- property 'stateNode' closes the circle
        at stringify (<anonymous>)

      at messageParent (node_modules/jest-runner/node_modules/jest-worker/build/workers/messageParent.js:29:19)
```

**Comment by broccolinisoup** [comment]
@ItzaMi Looking at the error on the `ConfirmationDialog.test.tsx` and see unexpected snapshot changes in the diff, I suspect you might not have the latest changes from the `main` branch.

If this is the case, could you please make sure your branch has the latest `main` merged?

After merging the `main`, please make sure to run consecutively `npm install`, `npm run build` and lastly `npm run test -- -u` to revert back the unexpected snapshots.

Sorry that it is taking longer, and I appreciate your patience with me 🙏🏻 

I think after going through the steps above, you might still have some failings in the `ConfirmationDialog.test.tsx`. We can resolve them by updating the deprecated `Button` and `ActionMenu` ([doc reference](https://primer.style/react/ActionMenu)).

Failings are related to the `expect(getByText('Primary')).toEqual(document.activeElement)` lines. Because we are now using the new Buttons, not the deprecated one, and the DOM structure is different in the new button. You can do `expect(getByRole('button', {name: 'Primary'})).toEqual(document.activeElement)` instead. Please let me know if you have any failings or need any help. Thanks so much!

**Comment by ItzaMi** [comment]
Sorry that this is taking so long, @broccolinisoup . It has been some time since I've had to battle so fiercely with tests 😄
I think I modified the tests for `ConfirmationDialog` accordingly but please double-check it! 💃

File: src/__tests__/ConfirmationDialog.test.tsx [hunk 3]
```diff
@@ -62,10 +63,12 @@ const ShorthandHookFromActionMenu = () => {
...
           <Box display="flex" flexDirection="column" alignItems="flex-start">
-            <ActionMenu
-              renderAnchor={props => <Button {...props}>{text}</Button>}
-              items={[{text: 'Show dialog', onAction: onButtonClick}]}
-            />
+            <ActionMenu>
+              <Button>{text}</Button>
+              <Button ref={buttonRef} onClick={onButtonClick}>
+                Show dialog
+              </Button>
```
Comment (broccolinisoup) [inline src/__tests__/ConfirmationDialog.test.tsx:70]:
```suggestion

              <ActionMenu.Button>{text}</ActionMenu.Button>
              <ActionMenu.Overlay>
                <ActionList>
                  <ActionList.Item onSelect={onButtonClick}>Show dialog</ActionList.Item>
                </ActionList>
              </ActionMenu.Overlay>

```

Comment (broccolinisoup) [reply src/__tests__/ConfirmationDialog.test.tsx]: The test might be succeeding but I added a suggestion to encourage the correct usage of `ActionList` according to the [docs](https://primer.style/react/ActionMenu/) 

We need to make sure to import `ActionList` as well. 

```
import {ActionList} from '../ActionList'
```

Let me know if you have any questions about this!

Comment (broccolinisoup) [reply src/__tests__/ConfirmationDialog.test.tsx]: @ItzaMi Sorry, I missed your commit! 

Seems like the only thing we are now missing is importing the `ActionList` to `src/__tests__/ConfirmationDialog.test.tsx`

```
import {ActionList} from '../ActionList'`
```

File: src/__tests__/ConfirmationDialog.test.tsx [hunk 4]
```diff
@@ -2,10 +2,10 @@ import {render as HTMLRender, fireEvent} from '@testing-library/react'
 import {axe} from 'jest-axe'
 import React, {useCallback, useRef, useState} from 'react'
 
-import {ActionMenu} from '../deprecated/ActionMenu'
+import {ActionMenu} from '../ActionMenu'
```
Comment (broccolinisoup) [inline src/__tests__/ConfirmationDialog.test.tsx:5]:
```suggestion
import {ActionMenu} from '../ActionMenu'
import {ActionList} from '../ActionList'`
```

File: src/__tests__/ConfirmationDialog.test.tsx [hunk 5]
```diff
@@ -45,6 +45,7 @@ const Basic = ({confirmButtonType}: Pick<React.ComponentProps<typeof Confirmatio
 const ShorthandHookFromActionMenu = () => {
   const confirm = useConfirm()
   const [text, setText] = useState('Show menu')
+  const buttonRef = useRef<HTMLButtonElement>(null)
```
Comment (broccolinisoup) [inline src/__tests__/ConfirmationDialog.test.tsx:48]:
```suggestion
```

File: src/__tests__/ConfirmationDialog.test.tsx [hunk 6]
```diff
@@ -62,10 +63,16 @@ const ShorthandHookFromActionMenu = () => {
...
-            />
+            <ActionMenu>
+
+              <ActionMenu.Button>{text}</ActionMenu.Button>
+              <ActionMenu.Overlay>
+                <ActionList>
+                  <ActionList.Item onSelect={onButtonClick}>Show dialog</ActionList.Item>
+                </ActionList>
+              </ActionMenu.Overlay>
+
```
Comment (broccolinisoup) [inline src/__tests__/ConfirmationDialog.test.tsx:74]:
```suggestion
```

File: src/__tests__/ConfirmationDialog.test.tsx [hunk 7]
```diff
@@ -62,10 +63,16 @@ const ShorthandHookFromActionMenu = () => {
       <SSRProvider>
         <BaseStyles>
           <Box display="flex" flexDirection="column" alignItems="flex-start">
-            <ActionMenu
-              renderAnchor={props => <Button {...props}>{text}</Button>}
-              items={[{text: 'Show dialog', onAction: onButtonClick}]}
-            />
+            <ActionMenu>
+
```
Comment (broccolinisoup) [inline src/__tests__/ConfirmationDialog.test.tsx:67]:
```suggestion
```

File: src/__tests__/ConfirmationDialog.test.tsx [hunk 8]
```diff
@@ -2,10 +2,11 @@ import {render as HTMLRender, fireEvent} from '@testing-library/react'
 import {axe} from 'jest-axe'
 import React, {useCallback, useRef, useState} from 'react'
 
-import {ActionMenu} from '../deprecated/ActionMenu'
+import {ActionMenu} from '../ActionMenu'
+import {ActionList} from '../ActionList'`
```
Comment (broccolinisoup) [inline src/__tests__/ConfirmationDialog.test.tsx:6]:
```suggestion
import {ActionList} from '../ActionList'
```

**Review by broccolinisoup — APPROVED** [review]
👋🏻 Hi @ItzaMi , so sorry that it took very long but i just pushed commits to fix some misc stuff which is tiny bits. All is looking good now!! Thank you so much for your patience and huge contributions to Primer 🎉 We appreciate it a ton 🙏🏻 

The only job is failing now is the  changeset job which we are discussing. I'll check back in again in the next few days and merge your PR. Thanks again 🙏🏻

File: .changeset/cool-schools-cheer.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+---
+'@primer/react': minor
+---
+
+[Dialog] Replaces deprecated button for current one
```
Comment (broccolinisoup) [inline .changeset/cool-schools-cheer.md:5]:
```suggestion
[Dialog] Replaces deprecated button for current one
<!-- Changed components: Dialog-->
```
