### PR TITLE
Remove `ConfirmationDialog` custom renders to ensure visual parity with `Dialog`

### LINKED ISSUE #7454: ConfirmationDialog header does not match Dialog’s
### Description

By overriding the default `renderHeader` function, some default styling of the Dialog gets stripped (header divider).

### Steps to reproduce

1. See https://primer.style/product/components/confirmation-dialog/ (no border under header)
2. See https://primer.style/product/components/dialog/ (header has a divider)

### Version

v35.2.0

### Browser

_No response_

### PR DESCRIPTION
**Pull request by HiroAgustin**
Closes #7454

### Changelog

Remove `ConfirmationDialog` custom renders to ensure visual parity with `Dialog`

| Before | After |
|--------|--------|
| Screenshot 2026-01-16 at 14 20 55 | Screenshot 2026-01-16 at 14 20 20 | 

Mainly this introduces a divider for the header, decreases the dialog’s title font size, and increases the default font size for the body of the confirmation dialog.

#### Removed

Custom renders for ConfirmationDialog, relying on default Dialog styling for header, body and footer.

### Rollout strategy

- [ ] Patch release
- [x] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [ ] None; if selected, include a brief description as to why

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [x] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [x] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

### CODE REVIEW

**Comment by HiroAgustin** [comment]
Looks like the failing test is a timeout unrelated to my changes, how can I re-trigger its execution?

**Comment by siddharthkp** [comment]
> Looks like the failing test is a timeout unrelated to my changes, how can I re-trigger its execution?

You can re-run the job from the job page: https://github.com/primer/react/actions/runs/21069835736/job/60596261386?pr=7455

**Comment by HiroAgustin** [comment]
@siddharthkp that did the trick! I see some pending checks, is there anything else pending on me?

File: packages/react/src/ConfirmationDialog/ConfirmationDialog.tsx [hunk 1]
```diff
@@ -81,39 +77,6 @@ export interface ConfirmationDialogProps {
...
-  return <div className={classes.ConfirmationBody}>{children}</div>
-}
-
-const ConfirmationFooter: React.FC<React.PropsWithChildren<DialogProps>> = ({footerButtons}) => {
-  const {containerRef: footerRef} = useFocusZone({
-    bindKeys: FocusKeys.ArrowHorizontal | FocusKeys.Tab,
-    focusInStrategy: 'closest',
-  })
-
-  // Must have exactly 2 buttons!
```
Comment (hectahertz) [inline packages/react/src/ConfirmationDialog/ConfirmationDialog.tsx:109]: Before merging, I'd have a look at why this was added, just in case.

I'd also have a look at why it was styled differently.

**Comment by siddharthkp** [comment]
> @siddharthkp that did the trick! I see some pending checks, is there anything else pending on me?

Yep, because there are newer commits, you'll need to run integration tests once more (https://github.com/primer/react/pull/7455#issuecomment-3758958360). (There is usually a comment that tells you that, for some reason, I don't see it here)

File: packages/react/src/ConfirmationDialog/ConfirmationDialog.tsx (hunk 1 above)
Comment (HiroAgustin) [reply packages/react/src/ConfirmationDialog/ConfirmationDialog.tsx:109]: The exactly 2 buttons remains, since those are generated internally in the component.

Who could I speak to regarding the styles?

Comment (HiroAgustin) [reply packages/react/src/ConfirmationDialog/ConfirmationDialog.tsx:109]: @lukasoppermann mentioned on the slack thread:

> I don't think they should be different. This is probably a change that was not propagated to both components.

Would this confirmation be enough?
